---
  extends:
    - "@ncigdc/buildjs-node"
  rules:
    no-console: 0
    max-len: 0

    fp/no-let: 0
    fp/no-mutation: 0
    fp/no-mutating-methods: 0
    fp/no-throw: 0

    import/no-dynamic-require: 0
    import/no-unresolved: 0
